rule run_vitessce:
    input:
        images=[
            "/Users/mkeller/research/dbmi/vitessce/jay-tarolli/human_3d.raster.pyramid.ome.tiff"
        ]
    output:
        "vitessce.config.json"
    params:
        name="Test",
        out_dir="data"
    threads: 1
    wrapper:
        "file:///Users/mkeller/research/dbmi/vitessce/snakemake-wrappers/"
