name: "vitessce ome-tiff"
description: Create a Vitessce configuration based on an OME-TIFF file.
url: https://github.com/keller-mark/vitessce-snakemake
authors:
  - Mark Keller
input:
  - images: OME-TIFF files containing microscopy images.
  - segmentations: OME-TIFF files containing bitmask segmentations.
output:
  - Vitessce JSON configuration file.
params:
  name: Configuration name.
  description: Configuration description.
  out_dir: Output directory for processed files.
  port: Port on which to serve processed files. By default, 8000.
notes: Multiple threads can be used during compression of the output file with ``pigz``.